# Generated by Django 5.1 on 2024-08-18 09:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="درباره ما")),
                (
                    "picture",
                    models.FileField(
                        upload_to="AboutUs/", verbose_name="تصویر درباره ما"
                    ),
                ),
                (
                    "text1",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات 1"
                    ),
                ),
                (
                    "text2",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات 2"
                    ),
                ),
                (
                    "text3",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات 3 "
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "درباره ما",
                "db_table": "AboutUs",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان سوال")),
                ("text", ckeditor.fields.RichTextField(verbose_name="متن")),
            ],
            options={
                "verbose_name_plural": "سوالات پر تکرار ",
                "db_table": "FAQ",
            },
        ),
    ]
