# Generated by Django 5.1 on 2024-08-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "family",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("text", models.TextField(verbose_name="متن")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pre", "بدون بررسی"),
                            ("now", "در حال بررسی"),
                            ("end", "تمام شده"),
                        ],
                        default="pre",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ارتباط با ما",
                "db_table": "ContactUs",
            },
        ),
    ]
