# Generated by Django 5.1 on 2024-08-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_contactus_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام حامی ما")),
                (
                    "picture",
                    models.FileField(upload_to="Supporter/", verbose_name="لوگو"),
                ),
            ],
            options={
                "verbose_name_plural": "Supporter",
                "db_table": "Supporter",
            },
        ),
    ]
