# Generated by Django 5.1 on 2024-08-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_supporter"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام تصویر")),
                (
                    "picture",
                    models.FileField(upload_to="MainSlider/", verbose_name="تصویر"),
                ),
            ],
            options={
                "verbose_name_plural": "تصاویر اسلایدر ابتدایی",
                "db_table": "MainSlider",
            },
        ),
    ]
