# Generated by Django 5.1 on 2024-08-19 10:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته بندی"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="آدرس دسته بندی")),
            ],
            options={
                "verbose_name_plural": "دسته بندی های وبلاگ",
                "db_table": "Category_Blog",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.FileField(upload_to="blog/Post/", verbose_name="")),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="عنوان دسته بندی"),
                ),
                ("slug", models.SlugField(verbose_name="آدرس اینترنتی")),
                (
                    "description1",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="توضیحات"),
                ),
                (
                    "description2",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="blog.category_blog",
                        verbose_name="دسته بندی ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "پست های وبلاگ",
                "db_table": "Post",
            },
        ),
    ]
