# Generated by Django 5.1 on 2024-08-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tags_post_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام پاسخ دهنده"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="ایمیل پاسخ دهنده"),
                ),
                ("text", models.TextField(verbose_name="متن پاسخ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("no_check", "بدون چک"),
                            ("checheck", "چک"),
                            ("pass", "تایید"),
                        ],
                        default="no_check",
                        max_length=20,
                        verbose_name="وضعیت بررسی کامنت",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "کامنت های وبلاگ",
                "db_table": "PostComment",
            },
        ),
    ]
