# Generated by Django 5.1 on 2024-08-22 20:41

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="times",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, null=True, verbose_name="زمان ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.FileField(upload_to="blog/Post/", verbose_name="تصویر"),
        ),
    ]
