# Generated by Django 5.1 on 2024-08-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("blog", "0004_post_times_alter_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.profile",
                verbose_name="نویسنده",
            ),
        ),
    ]
