# Generated by Django 5.1 on 2024-08-23 19:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summer_text",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="خلاصه متن"),
        ),
        migrations.AddField(
            model_name="post",
            name="time_to_read",
            field=models.PositiveIntegerField(null=True, verbose_name="زمان  خواندن"),
        ),
    ]
