# Generated by Django 5.1 on 2024-08-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_summer_text_post_time_to_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="post_selected",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="پست انتخاب شده",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(max_length=100, verbose_name="عنوان پست"),
        ),
    ]
