# Generated by Django 4.2.15 on 2024-08-17 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تلفن')),
                ('picture', models.FileField(blank=True, null=True, upload_to='Profile/Picture/')),
                ('code_melli', models.CharField(blank=True, max_length=10, null=True)),
                ('hb', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس منزل')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'مشخصات دقیق حساب کاربری',
                'db_table': 'Profile',
            },
        ),
    ]
